name: Publish guide

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  REPO: actions-test

jobs:
  publish:
    name: Publish guide
    env:
      MDBOOK_VERSION: 0.4.7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mdbook
        run: |
          curl -LsSf https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          echo $(pwd) >> $GITHUB_PATH
      - name: Run mdbook
        run: |
          mdbook build guide
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: guide/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
