name: Rust

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: actions-test
            asset_name: actions-test-$tag-linux-amd64
          - os: windows-latest
            artifact_name: actions-test.exe
            asset_name: actions-test-$tag-windows-amd64
          - os: macos-latest
            artifact_name: actions-test
            asset_name: actions-test-$tag-macos-amd64

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --locked
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
