name: Release

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always
  REPO: actions-test

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            env:
                EXTENSION: ""
                OS_NAME: "linux-amd64"
          - os: windows-latest
            env:
                EXTENSION: ".exe"
                OS_NAME: "macos-amd64"
          - os: macos-latest
            env:
                EXTENSION: ""
                OS_NAME: "linux-amd64"

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          cargo build --release
          cp -f target/release/actions-test . > /dev/null
          tar -czf actions-test-${{ env.RELEASE_VERSION }}-${{ matrix.os }}.tar.gz $REPO$EXTENSION
          ls
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: actions-test-${{ env.RELEASE_VERSION }}-${{ matrix.os }}.tar.gz
          asset_name: actions-test-${{ env.RELEASE_VERSION }}-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
